### ISSUE TITLE
Wire compatibility of messages sent by legacy transport broken in 2.0.1 release

### ISSUE THREAD

**Issue by boblangley** [Particular/NServiceBus.Transport.AzureServiceBus#454]
**Describe the bug**
While upgrading to the `Azure.Messaging.ServiceBus` SDK the capability to property decode messages using the `wcf/byte-array` encoding was removed, resulting in wire incompatibility with endpoints sending messages using the [legacy Azure Service Bus transport](https://docs.particular.net/transports/azure-service-bus/compatibility).

Example stack trace (using JSON serialization):

```
NServiceBus.MessageDeserializationException: An error occurred while attempting to extract logical messages from incoming physical message 00000000-0000-0000-0000-000000000000 ---> Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: @. Path '', line 0, position 0.
at Newtonsoft.Json.JsonTextReader.ParseValue()
at NServiceBus.Newtonsoft.Json.JsonMessageSerializer.IsArrayStream(Stream stream)
at NServiceBus.Newtonsoft.Json.JsonMessageSerializer.Deserialize(Stream stream, IList`1 messageTypes)
at NServiceBus.DeserializeMessageConnector.Extract(IncomingMessage physicalMessage) in /_/src/NServiceBus.Core/Pipeline/Incoming/DeserializeMessageConnector.cs:line 119
at NServiceBus.DeserializeMessageConnector.ExtractWithExceptionHandling(IncomingMessage message) in /_/src/NServiceBus.Core/Pipeline/Incoming/DeserializeMessageConnector.cs:line 47
--- End of inner exception stack trace ---
at NServiceBus.DeserializeMessageConnector.ExtractWithExceptionHandling(IncomingMessage message) in /_/src/NServiceBus.Core/Pipeline/Incoming/DeserializeMessageConnector.cs:line 51
at NServiceBus.DeserializeMessageConnector.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Pipeline/Incoming/DeserializeMessageConnector.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NServiceBus.ProcessingStatisticsBehavior.<Invoke>d__0.MoveNext() in /_/src/NServiceBus.Core/Performance/Statistics/ProcessingStatisticsBehavior.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NServiceBus.TransportReceiveToPhysicalMessageConnector.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Pipeline/Incoming/TransportReceiveToPhysicalMessageConnector.cs:line 39
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NServiceBus.RetryAcknowledgementBehavior.<Invoke>d__2.MoveNext() in /_/src/NServiceBus.Core/ServicePlatform/Retries/RetryAcknowledgementBehavior.cs:line 27
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NServiceBus.MainPipelineExecutor.<Invoke>d__1.MoveNext() in /_/src/NServiceBus.Core/Pipeline/MainPipelineExecutor.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at NServiceBus.Transport.AzureServiceBus.MessagePump.<ReceiveMessage>d__25.MoveNext() in /_/src/Transport/Receiving/MessagePump.cs:line 239
```

**To Reproduce**

1. Send a message from an endpoint using the legacy transport
2. Process the message on an endpoint using version 2.0.1 of this transport.

**Expected behavior**

The message is successfully processed when received from an endpoint running the legacy transport.

**Versions:**
 - NuGet package: 2.0.1
 - OS: Any
 - .NET Version: Any supported version

**Additional context**

Relates to: https://github.com/Particular/ServiceControl/issues/2745

**Comment by boblangley** [comment]
We have reproduced the bug and are working on a release now with the fix.

**Comment by boblangley** [comment]
Version 2.0.2 has been released.
