### ISSUE TITLE
Wrong ServiceBusAdministrationClient constructor called when using TokenCredential

### ISSUE THREAD

**Issue by LarsCelie** [Particular/NServiceBus.Transport.AzureServiceBus#588]
**Describe the bug**
ServiceBusAdministrationClient constructor called with `connectionstring` and `tokencredential` parameters.
But actual parameters are `fullyQualifiedNamespace` and `tokenCredential`.

This result in the following exception:
`System.ArgumentException: The value 'Endpoint=sb://my-namespace.servicebus.windows.net/' is not a well-formed Service Bus fully qualified namespace. (Parameter 'fullyQualifiedNamespace')`

**To Reproduce**
Construct AzureServiceBusTransportInfrastructure with a connection string and a TokenCredential

**Expected behavior**
No exception

**Versions:**
 - 2.0.0 -2.0.3 of NServiceBus.Transport.AzureServiceBus

**Additional context**
https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/blob/2.0.3/src/Transport/AzureServiceBusTransportInfrastructure.cs#L53

Actual constructor: https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.administration.servicebusadministrationclient.-ctor?view=azure-dotnet#azure-messaging-servicebus-administration-servicebusadministrationclient-ctor(system-string-azure-core-tokencredential)

Working code:
```c#
var connectionStringProperties = Azure.Messaging.ServiceBus.ServiceBusConnectionStringProperties.Parse(ConnectionString);
new ServiceBusAdministrationClient(connectionStringProperties.FullyQualifiedNamespace, new Azure.Identity.DefaultAzureCredential());
```

Stacktrace:
```txt
System.ArgumentException: The value 'Endpoint=sb://my-namespace.servicebus.windows.net/' is not a well-formed Service Bus fully qualified namespace. (Parameter 'fullyQualifiedNamespace')
at Azure.Core.Argument.AssertWellFormedServiceBusNamespace(String argumentValue, String argumentName)
at Azure.Messaging.ServiceBus.Administration.ServiceBusAdministrationClient..ctor(String fullyQualifiedNamespace,   ServiceBusTokenCredential credential, ServiceBusAdministrationClientOptions options)
at Azure.Messaging.ServiceBus.Administration.ServiceBusAdministrationClient..ctor(String fullyQualifiedNamespace, TokenCredential credential)
at NServiceBus.Transport.AzureServiceBus.AzureServiceBusTransportInfrastructure..ctor(SettingsHolder settings, String connectionString) in /_/src/Transport/AzureServiceBusTransportInfrastructure.cs:line 52
at NServiceBus.AzureServiceBusTransport.Initialize(SettingsHolder settings, String connectionString) in /_/src/Transport/AzureServiceBusTransport.cs:line 16
at NServiceBus.TransportSeam.Create(Settings transportSettings, Configuration hostingConfiguration) in /_/src/NServiceBus.Core/Transports/TransportSeam.cs:line 20
at NServiceBus.EndpointCreator.Initialize() in /_/src/NServiceBus.Core/EndpointCreator.cs:line 44
at NServiceBus.EndpointCreator.Create(SettingsHolder settings, Configuration hostingConfiguration) in /_/src/NServiceBus.Core/EndpointCreator.cs:line 25
at NServiceBus.HostCreator.CreateWithExternallyManagedContainer(EndpointConfiguration endpointConfiguration, IConfigureComponents externalContainer) in /_/src/NServiceBus.Core/Hosting/HostCreator.cs:line 34
at NServiceBus.EndpointWithExternallyManagedContainer.Create(EndpointConfiguration configuration, IConfigureComponents configureComponents) in /_/src/NServiceBus.Core/EndpointWithExternallyManagedContainer.cs:line 20
```

**Comment by ramonsmits** [comment]
@LarsCelie Thanks for reporting! How is this affecting you at the moment? Based on our bug triage it would not be dealt with priority.

**Comment by LarsCelie** [comment]
@ramonsmits We're in the process of upgrading our services from dotnetcore 3.1 to dotnet 6. We upgraded this package from 1.9.0 to 2.03 as part of our efforts to update all dependencies.

**Comment by ramonsmits** [comment]
@LarsCelie Using TokenCredential did work correctly with 1.x for you? Also, can you share your customer details? You may also provide that via <support@particular.net> and reference this issue.

**Comment by LarsCelie** [comment]
It worked differently in 1.x, but that worked fine:

```
-transport.CustomTokenProvider(TokenProvider.CreateManagedIdentityTokenProvider());
+transport.CustomTokenCredential(new DefaultAzureCredential());
```

**Comment by ramonsmits** [comment]
@LarsCelie This issue prevents you to migrate from 1.x to 2.x, thanks for those details.

**Comment by ramonsmits** [comment]
Created the following enhancement issue to improve the experience:

- https://github.com/Particular/NServiceBus.Transport.AzureServiceBus/issues/604
