### ISSUE TITLE
Fails silently when unable to connect

### ISSUE THREAD

**Issue by martinosk** [Particular/NServiceBus.Transport.AzureServiceBus#8]
For unknown reasons, receiving and sending messages fails if I do not I specify "transport.UseWebSockets();".
The endpoint starts and queues + subscriptions are created but send and recieve fails.

The log from NServiceBus does not help. Only entries are:

> 2018-08-24 10:56:39.294 INFO  DefaultFactory Logging to '...\netcoreapp2.1\' with level Info
> 2018-08-24 10:56:39.667 INFO  NServiceBus.LicenseManager No valid license could be found. Falling back to trial license with start date '2018-08-23'.

The following exceptions can be seen in the debug output: 

> Exception thrown: 'System.Net.Sockets.SocketException' in System.Private.CoreLib.dll
> Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusCommunicationException' in Microsoft.Azure.ServiceBus.dll
> Exception thrown: 'Microsoft.Azure.ServiceBus.ServiceBusCommunicationException' in System.Private.CoreLib.dll

**Comment by bording** [comment]
@martinosk What do you mean by "The endpoint starts and queues + subscriptions are created but send and recieve fails."

There should be some sort of exception being thrown if the message pump can't consume messages from a queue. There should also be an exception thrown if a send fails.

Are you seeing any exceptions being thrown?

In general, if you require `UseWebSockets`, that means you have some sort of firewall blocking the AMQP traffic that Azure Service Bus uses by default.

**Comment by SeanFeldman** [comment]
@martinosk ASBS transport is using ASB .NET Standard client, which by default is using TCP port 5671. If TCP port is blocked, WebSockets is an alternative that uses TCP port 443. If non of these ports is opened, the client will fail to communicate and the transport will not work.

Please share with us exception details just like @bording has suggested.
Additionally, please try to run your code from another machine/environment (outside of your office).

**Comment by martinosk** [comment]
The connection issue is just a firewall problem, I am only worried about the lack of logging and silent exceptions. 
On send, an exception is thrown, which is fine. But the exception is not logged by the NServiceBus logger.
When consuming messages I can see the exceptions in the debug output, but they are not thrown or logged to the NServiceBus log.

**Comment by SeanFeldman** [comment]
@martinosk the issue seems to be with the ASB client that keeps retrying before throwing an exception.
After about a minute it does throw:

![image](https://user-images.githubusercontent.com/1309622/44701469-216f9f80-aa4c-11e8-831b-5ce2da8864db.png)

ASBS transport bubbles it up.

```
Microsoft.Azure.ServiceBus.ServiceBusCommunicationException
  HResult=0x80131500
  Message=An attempt was made to access a socket in a way forbidden by its access permissions ErrorCode: AccessDenied
  Source=Microsoft.Azure.ServiceBus
  StackTrace:
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<OnSendAsync>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.<SendAsync>d__39.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MutateOutgoingTransportMessageBehavior.<InvokeOutgoingTransportMessageMutators>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.SerializeMessageConnector.<Invoke>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.MutateOutgoingMessageBehavior.<InvokeOutgoingMessageMutators>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.UnicastSendRouterConnector.<Invoke>d__1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Program.<Main>d__0.MoveNext() in C:\github\nsb\docs.particular.net\samples\azure-service-bus-netstandard\send-reply\ASBS_1\Endpoint1\Program.cs:line 57
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Program.<Main>()

Inner Exception 1:
SocketException: An attempt was made to access a socket in a way forbidden by its access permissions
```

**Comment by SeanFeldman** [comment]
@martinosk while ASB client is throwing an exception after 39 seconds, that is not bubbling up.
I'm looking into this.

**Comment by SeanFeldman** [comment]
@martinosk have you had a chance to try the latest release of the transport and ASB client (3.3.0)?

**Comment by martinosk** [comment]
@SeanFeldman Just gave it a quick try, connection exception now bubbles all the way up. Thanks :)
